{{- if .Values.api.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agentlens.fullname" . }}-api
  labels:
    {{- include "agentlens.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "agentlens.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "agentlens.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: CLICKHOUSE_HOST
              value: {{ include "agentlens.fullname" . }}-clickhouse
            - name: REDIS_URL
              value: "redis://{{ include "agentlens.fullname" . }}-redis-master:6379/0"
            - name: KAFKA_BROKERS
              value: "{{ include "agentlens.fullname" . }}-kafka:9092"
          envFrom:
            - configMapRef:
                name: {{ include "agentlens.fullname" . }}-config
            - secretRef:
                name: {{ include "agentlens.fullname" . }}-secrets
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
{{- end }}
